### PR TITLE
Prevent warning message during converting cp949 file

### PR DESCRIPTION
**Pull request by yoonian**
Just remove below message.

> Errors occurred while converting **your file** with EUC-KR encoding.
> WARNING: Continue to load this file using EUC-KR, malformed data will be ignored.
> Press "Cancel" to choose another encoding manually.

### CODE REVIEW

**Comment by CBack83** [comment]
had be solved?

**Comment by seanliang** [comment]
@CBack83 Do you meet any problem with CP949 encoding?

**Comment by CBack83** [comment]
@seanliang Yes, I can't view CP949 encoding..

**Comment by seanliang** [comment]
@CBack83 Please create another issue and provide more information (sample file, error message, screenshot, etc) there.

**Pull request merged**
